### ISSUE TITLE
Add CWD as a MapGroup in server

### ISSUE THREAD

**Issue by KateMMiller** [NCRN/VegShiny#11]

**Comment by sjperles** [comment]
Make sure Coarse Woody Debris pulls down in Map Controls as a choice under PlantTypes

Add CWD Volume to PlantValueControl in "tags$div(title="Type of data to map",uiOutput("PlantValueControl")),"

Choose a species and Filter by Species becomes "greyed" or "hidden" when CWD is selected
--
